  name: Build upon Pull Request
  on: pull_request
  jobs:
    assemble_job:
      name: Assemble
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Assemble Debug
          run: ./gradlew assembleDebug
